version: '2'

tasks:
  
  gen:
    cmds:
      - go generate

  build-arm:
    deps: [gen]
    cmds:
      - GOOS=linux GOARCH=arm GOARM=7 go build -o feednotifier_armv7 cmd/*
  
  build:
    deps: [gen]
    cmds:
      - go build -o feednotifier cmd/*
  
  default:
    deps: [test]
    cmds:
      - task: build
  
  test:
    cmds:
      - go test
